// test.js
// Generated by ChatGPT

// chores
console.log('Login test activated...');
const { Client, GatewayIntentBits } = require('discord.js');
const config = require('./config.json');
const client = new Client({ intents: [GatewayIntentBits.Guilds] });

// core
console.log('Searching for bot token in config.json...');
client.login(config.token)
	.then(() => console.log('Token loaded...'))
	.then(() => console.log('Logged in!'))
	.catch(() => console.log('Login failed'))
	.finally(() => client.destroy());
